{
 "title": "Loki System Monitoring",
 "tags": [
  "loki",
  "monitoring"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "panels": [
  {
   "title": "Loki Ingestion Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "rate(loki_distributor_ingester_appended_entries_total[5m])",
     "legendFormat": "Log Ingest Rate"
    }
   ]
  },
  {
   "title": "Loki RAM Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "loki_ingester_memory_usage_bytes",
     "legendFormat": "Memory Usage"
    }
   ]
  },
  {
   "title": "Loki Chunk Storage Size",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(loki_chunk_store_chunk_bytes_total)",
     "legendFormat": "Chunk Storage Size"
    }
   ]
  }
 ]
}