# Loki configuration file
  ###start

auth_enabled: false

common:
  path_prefix: /loki

server: 
  http_listen_port: 3100
  grpc_listen_port: 9095
  log_level: info 

query_scheduler:
  max_outstanding_requests_per_tenant: 1024

querier:
  query_ingesters_within: 2h

storage_config:
  tsdb_shipper:
    active_index_directory: /loki/index
    cache_location: /loki/cache 
  filesystem:
    directory: /loki/chunks 

  # Enable schema config for structured metadata
schema_config:
  configs:
    - from: 2020-10-15
      store: tsdb  # Use 'tsdb' index type for structured metadata
      object_store: filesystem
      schema: v13  # Upgrade to schema v13
      index:
        prefix: index_
        period: 24h
limits_config:
  max_cache_freshness_per_query: '10m'
  reject_old_samples: true
  reject_old_samples_max_age: 30m
  ingestion_rate_mb: 10
  ingestion_burst_size_mb: 20
  split_queries_by_interval: 15m
  volume_enabled: true
  max_streams_per_user: 50000
  max_global_streams_per_user: 0
  max_label_name_length: 1024
  max_label_value_length: 2048
  max_label_names_per_series: 30

ingester:
  lifecycler:
    ring:
      kvstore:
        store: inmemory
      replication_factor: 1

    final_sleep: 0s
    heartbeat_timeout: 1m
    join_after: 0s
    num_tokens: 128
    min_ready_duration: 0s 
  chunk_idle_period: 5m
  chunk_retain_period: 30s
 
compactor:
  working_directory: /loki/compactor
  retention_enabled: false 
##end

  